version: '3.3'
volumes:
  db:
    driver:
      local
services:
  db:
    image: mysql/mysql-server:5.6
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
